#!/bin/bash

# project ID and download folder are passed as arguments
project_dir=$(readlink -f "$1")
project_id="$2"

# define global file names
project_base="${project_dir}/${project_id}"
project_log="${project_base}.log"
project_metapept="${project_base}.metapept"

# open log file
exec 3>> "${project_log}"

# write error messages to log file
exec 2>&3

# log start of project download
echo "started metapept of project ${project_id} @ $(date)" 1>&3

# drop previous version of the project metapeptidome (if present)
rm -f "${project_metapept}"

# collect all unique peptides from the sample metapeptidomes in the project metapeptidome
cat "${project_dir}"/*.prot2pept | grep -v '^>' | sort --temporary-directory="${project_dir}" | uniq > "${project_metapept}"

# log end of project download
echo "finished metapept of project ${project_id} @ $(date)" 1>&3
