#!/bin/bash

# process command line arguments
sample_prot=$(readlink -f "$1")

# define global file names
sample_metapept="${sample_prot}.metapept"
sample_pept2lca="${sample_prot}.pept2lca"
sample_log="${sample_prot}.log"

# open log file
exec 3> "${sample_log}"

# write error messages to log file
exec 2>&3

echo "started processing of ${sample_prot} @ $(date)" 1>&3

# step2: determine LCA for each peptide in metapeptidome (set of tryptic peptides occuring in the sample)

# remove FASTA header lines
grep -v '^>' "${sample_prot2pept}" | \
# deduplicate peptidome (set of peptides)
  sort | uniq | \
# save peptidome to disk (optional)
  tee "${sample_metapept}" | \
# compute LCA for each peptide in peptidome
  unipept pept2lca | \
# only retain peptide and taxon ID of LCA (save disk space)
  awk -F, -v OFS=',' '{print $1, $2}' > "${sample_pept2lca}"

echo "finished processing of ${sample_prot} @ $(date)" 1>&3

# close log file
exec 3>&-
