#!/bin/bash

# process command line arguments
project_dir=$(readlink -f "$1")
sample_id="$2"

# define global file names
sample_base="${project_dir}/${sample_id}"
sample_metaprot="${sample_base}.cds"
sample_prot2pept="${sample_base}.prot2pept"
sample_log="${sample_base}.log"

# open log file
exec 3>> "${sample_log}"

# write error messages to log file
exec 2>&3

echo "started prot2pept of sample ${sample_id} @ $(date)" 1>&3

# step1: parse FASTA file and break each protein sequence into its tryptic peptides;
#        this step is needed to be able to aggregate the tryptic peptides back to the
#        protein or DNA read level
prot2pept < "${sample_metaprot}" | peptfilter > "${sample_prot2pept}"

echo "finished prot2pept of sample ${sample_id} @ $(date)" 1>&3
