#!/bin/bash

# project ID and download folder are passed as arguments
project_dir=$(readlink -f "$1")
project_id="$2"

# define global file names
project_base="${project_dir}/${project_id}"
project_log="${project_base}.log"
project_prot2pept2lca="${project_base}.prot2pept2lca"
project_phyla="${project_base}.phyla"

# open log file
exec 3>> "${project_log}"

# write error messages to log file
exec 2>&3

# log start of this processsing step
echo "started slice phylum of project ${project_id} @ $(date)" 1>&3

# lookup complete lineage for each taxon found in one of the samples
find "${project_dir}" -maxdepth 1 -name '*.cds' | \
  sed 's+.*/\(.*\)\.cds+\1+' | \
  while read sample_id; do
    echo ">${sample_id}" > "${project_dir}/${sample_id}.phyla"
    python3 usmp_sample_slice_phylum.py < "${project_dir}/${sample_id}.prot2pept2lca" >> "${project_dir}/${sample_id}.phyla" &
  done

# wait until all child processes have finished executing
wait

# log end of this processing step
echo "finished slice phylum of project ${project_id} @ $(date)" 1>&3
