#!/bin/bash

# project ID and download folder are passed as arguments
project_dir=$(readlink -f "$1")
project_id="$2"

# define global file names
project_base="${project_dir}/${project_id}"
project_log="${project_base}.log"

# open log file
exec 3>> "${project_log}"

# write error messages to log file
exec 2>&3

# log start of project download
echo "started prot2pept of project ${project_id} @ $(date)" 1>&3

# sequentially process samples
find "${project_dir}" -maxdepth 1 -name '*.cds' | sed -e 's/^.*\/\(.*\)\.cds$/\1/' | while read sample_id; do
    usmp_sample_prot2pept "${project_dir}" "${sample_id}" > /dev/null 2>&1 &
done

# wait until all child processes have finished executing
wait

# log end of project download
echo "finished prot2pept of project ${project_id} @ $(date)" 1>&3
