#!/bin/bash

# project ID and download folder are passed as arguments
project_dir=$(readlink -f "$1")
project_id="$2"
sample_id="$3"

# define global file names
project_base="${project_dir}/${project_id}"
project_pept2lca="${project_base}.pept2lca"
project_taxa="${project_base}.taxa"
sample_base="${project_dir}/${sample_id}"
sample_prot2pept="${sample_base}.prot2pept"
sample_prot2pept2lca="${sample_base}.prot2pept2lca"

echo "started prot2pept2lca of sample ${sample_id} @ $(date)" 1>&3

# join prot -> pept -> taxon
join_first2last "${project_pept2lca}" "${sample_prot2pept}" | \
    join_first2last "${project_taxa}" - > "${sample_prot2pept2lca}"

echo "finished prot2pept2lca of sample ${sample_id} @ $(date)" 1>&3
