#!/bin/bash

# project ID and download folder are passed as arguments
project_dir=$(readlink -f "$1")
project_id="$2"

# define global file names
project_base="${project_dir}/${project_id}"
project_taxa="${project_base}.taxa"
project_log="${project_base}.log"

# open log file
exec 3>> "${project_log}"

# write error messages to log file
exec 2>&3

# log start of this processing step
echo "started lca2taxa of project ${project_id} @ $(date)" 1>&3

# lookup complete lineage for each taxon found in one of the samples
find "${project_dir}" -maxdepth 1 -name '*.pept2lca' -print0 | \
  xargs -0 cut -d, -f2 | \
  sort | uniq | \
  unipept taxonomy -a > "${project_taxa}"

# log end of this processing step
echo "finished lca2taxa of project ${project_id} @ $(date)" 1>&3
