#!/bin/bash
# Vraagt taxon naam en taxon rang op wanneer enkel taxon id is gegeven.

usage(){ echo "Syntax: $(basename $0) [-k k(Integer)] [-t tt1-tt2-...] namePrefix" 1>&2; exit 1;}

translationTables="1 2 3 4 5 6 9 10 11"
while getopts ":t:k:" opt; do
        case $opt in
                t) translationTables=$(echo "$OPTARG" | tr '-' ' ')     ;;
		k) k=$OPTARG ;;
                :) usage ;;
                \?) usage
  esac
done
shift $((OPTIND - 1))

if [ $# -ne 1 ]
then 
	usage
fi

name="$1"

for i in $translationTables
do 
	lca_file="$name.$i.${k}mer.lca"
	while read line
	do 
		if [ ! ${line:0:1} = ">" ]
		then 
			tax_id=$(echo $line | cut -d , -f 2) 
			tax_info=$(unipept taxonomy $tax_id | sed -n "2p" |sed 's/^[0-9]*,//')
			echo "$line,$tax_info" >> lca_file.temp
		else
			echo "$line" >> lca_file.temp
		fi 
	done < $lca_file
	mv lca_file.temp "$lca_file"
done	 
